config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:update,:destroy]
  resources :books do
    resource :favorites, only: [:create,:destroy]
    resource :book_comments, only: [:create]
  end
  resources :book_comments, only: [:destroy]

  devise_for :users
  resources :users, only: [:index,:show,:edit,:update]
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]

  get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :view_counts, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited?(user, book)
    Favorite.find_by(user_id: user.id, book_id: book.id).present?
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @book_comments = BookComment.where(book_id: params[:id])
    if ViewCount.find_by(user_id: current_user.id, book_id: @book.id).nil?
      current_user.view_counts.create(book_id: @book.id)
    end
  end

  def index
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorited_users).
      sort_by {|x|
        x.favorited_users.includes(:favorites).where(created_at: from...to).size
      }.reverse
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless user_is_book_owner?
       redirect_to book_path(@book), alert: "You are not authorized to edit information in this book."
    end
  end

  def update
    @book = Book.find(params[:id])
    if user_is_book_owner?
      if @book.update(book_params)
        redirect_to book_path(@book), notice: "You have updated book successfully."
      else
        render "edit"
      end
    else
      redirect_to book_path(@book), alert: "You are not authorized to edit information in this book."
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to user_path(current_user)
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

  def user_is_book_owner?
    @book.user_id == current_user.id
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<% if book.presence && book.errors.any? %>
  <div class = "alert">
    <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% if books.present? %>
      <% books.each do |book| %>
        <tr>
          <td><%= link_to(book.user) do %>
            <%= image_tag book.user.get_profile_image, size:'50x50' %>
            <% end %>
          </td>
          <td><%= link_to book.title,book %></td>
          <td><%= book.body %></td>
          <td id="favorite_buttons_<%= book.id %>">
            <%= render "favorites/favorites", book: book %>
          </td>
          <td>コメント数: <%= book.book_comments.size%></td>
          <td>閲覧数: <%= book.view_counts.size %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td>閲覧数: <%= @book.view_counts.size %></td>
          <% if current_user == @book.user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>
      <table>
        <% @book_comments.present? && @book_comments.each do |book_comment| %>
    		  <tr>
            <td><%= link_to(book_comment.user) do %>
              <%= image_tag book_comment.user.get_profile_image, size:"50x50" %><br>
              <%= book_comment.user.name %>
              <% end %>
            </td>
            <td><%= book_comment.comment %></td>
            <% if current_user == book_comment.user %>
              <td><%= link_to 'Destroy', book_comment_path(book_comment.id), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
            <% end %>
          </tr>
        <% end %>
      </table>
      <%= form_with model: [@book, @book_comment], local:true do |f| %>
        <div class="form-group">
          <%= f.text_area :comment, rows:'5', class: 'form-control book_book_comment' %>
        </div>
        <div class="form-group">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>
    </div>
  </div>
</div>